//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//


package org.medee.playground.upnp.didllite.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for channelID_at_type.wc.values.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="channelID_at_type.wc.values">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="ANALOG"/>
 *     &lt;enumeration value="DIGITAL"/>
 *     &lt;enumeration value="FREQUENCY"/>
 *     &lt;enumeration value="SI"/>
 *     &lt;enumeration value="LINE"/>
 *     &lt;enumeration value="NETWORK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "channelID_at_type.wc.values", namespace = "urn:schemas-upnp-org:av:av")
@XmlEnum
public enum ChannelIDAtTypeWcValues {

    ANALOG,
    DIGITAL,
    FREQUENCY,
    SI,
    LINE,
    NETWORK;

    public String value() {
        return name();
    }

    public static ChannelIDAtTypeWcValues fromValue(String v) {
        return valueOf(v);
    }

}
