//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//


package org.medee.playground.upnp.didllite.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for className.wc.type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="className.wc.type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NCName">
 *     &lt;enumeration value="object.item"/>
 *     &lt;enumeration value="object.item.imageItem"/>
 *     &lt;enumeration value="object.item.imageItem.photo"/>
 *     &lt;enumeration value="object.item.audioItem"/>
 *     &lt;enumeration value="object.item.audioItem.musicTrack"/>
 *     &lt;enumeration value="object.item.audioItem.audioBroadcast"/>
 *     &lt;enumeration value="object.item.audioItem.audioBook"/>
 *     &lt;enumeration value="object.item.videoItem"/>
 *     &lt;enumeration value="object.item.videoItem.movie"/>
 *     &lt;enumeration value="object.item.videoItem.videoBroadcast"/>
 *     &lt;enumeration value="object.item.videoItem.musicVideoClip"/>
 *     &lt;enumeration value="object.item.playlistItem"/>
 *     &lt;enumeration value="object.item.textItem"/>
 *     &lt;enumeration value="object.item.bookmarkItem"/>
 *     &lt;enumeration value="object.item.epgItem"/>
 *     &lt;enumeration value="object.item.epgItem.audioProgram"/>
 *     &lt;enumeration value="object.item.epgItem.videoProgram"/>
 *     &lt;enumeration value="object.container.person"/>
 *     &lt;enumeration value="object.container.person.musicArtist"/>
 *     &lt;enumeration value="object.container.playlistContainer"/>
 *     &lt;enumeration value="object.container.album"/>
 *     &lt;enumeration value="object.container.album.musicAlbum"/>
 *     &lt;enumeration value="object.container.album.photoAlbum"/>
 *     &lt;enumeration value="object.container.genre"/>
 *     &lt;enumeration value="object.container.genre.musicGenre"/>
 *     &lt;enumeration value="object.container.genre.movieGenre"/>
 *     &lt;enumeration value="object.container.channelGroup"/>
 *     &lt;enumeration value="object.container.channelGroup.audioChannelGroup"/>
 *     &lt;enumeration value="object.container.channelGroup.videoChannelGroup"/>
 *     &lt;enumeration value="object.container.epgContainer"/>
 *     &lt;enumeration value="object.container.storageSystem"/>
 *     &lt;enumeration value="object.container.storageVolume"/>
 *     &lt;enumeration value="object.container.storageFolder"/>
 *     &lt;enumeration value="object.container.bookmarkFolder"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "className.wc.type")
@XmlEnum
public enum ClassNameWcType {

    @XmlEnumValue("object.item")
    OBJECT_ITEM("object.item"),
    @XmlEnumValue("object.item.imageItem")
    OBJECT_ITEM_IMAGE_ITEM("object.item.imageItem"),
    @XmlEnumValue("object.item.imageItem.photo")
    OBJECT_ITEM_IMAGE_ITEM_PHOTO("object.item.imageItem.photo"),
    @XmlEnumValue("object.item.audioItem")
    OBJECT_ITEM_AUDIO_ITEM("object.item.audioItem"),
    @XmlEnumValue("object.item.audioItem.musicTrack")
    OBJECT_ITEM_AUDIO_ITEM_MUSIC_TRACK("object.item.audioItem.musicTrack"),
    @XmlEnumValue("object.item.audioItem.audioBroadcast")
    OBJECT_ITEM_AUDIO_ITEM_AUDIO_BROADCAST("object.item.audioItem.audioBroadcast"),
    @XmlEnumValue("object.item.audioItem.audioBook")
    OBJECT_ITEM_AUDIO_ITEM_AUDIO_BOOK("object.item.audioItem.audioBook"),
    @XmlEnumValue("object.item.videoItem")
    OBJECT_ITEM_VIDEO_ITEM("object.item.videoItem"),
    @XmlEnumValue("object.item.videoItem.movie")
    OBJECT_ITEM_VIDEO_ITEM_MOVIE("object.item.videoItem.movie"),
    @XmlEnumValue("object.item.videoItem.videoBroadcast")
    OBJECT_ITEM_VIDEO_ITEM_VIDEO_BROADCAST("object.item.videoItem.videoBroadcast"),
    @XmlEnumValue("object.item.videoItem.musicVideoClip")
    OBJECT_ITEM_VIDEO_ITEM_MUSIC_VIDEO_CLIP("object.item.videoItem.musicVideoClip"),
    @XmlEnumValue("object.item.playlistItem")
    OBJECT_ITEM_PLAYLIST_ITEM("object.item.playlistItem"),
    @XmlEnumValue("object.item.textItem")
    OBJECT_ITEM_TEXT_ITEM("object.item.textItem"),
    @XmlEnumValue("object.item.bookmarkItem")
    OBJECT_ITEM_BOOKMARK_ITEM("object.item.bookmarkItem"),
    @XmlEnumValue("object.item.epgItem")
    OBJECT_ITEM_EPG_ITEM("object.item.epgItem"),
    @XmlEnumValue("object.item.epgItem.audioProgram")
    OBJECT_ITEM_EPG_ITEM_AUDIO_PROGRAM("object.item.epgItem.audioProgram"),
    @XmlEnumValue("object.item.epgItem.videoProgram")
    OBJECT_ITEM_EPG_ITEM_VIDEO_PROGRAM("object.item.epgItem.videoProgram"),
    @XmlEnumValue("object.container.person")
    OBJECT_CONTAINER_PERSON("object.container.person"),
    @XmlEnumValue("object.container.person.musicArtist")
    OBJECT_CONTAINER_PERSON_MUSIC_ARTIST("object.container.person.musicArtist"),
    @XmlEnumValue("object.container.playlistContainer")
    OBJECT_CONTAINER_PLAYLIST_CONTAINER("object.container.playlistContainer"),
    @XmlEnumValue("object.container.album")
    OBJECT_CONTAINER_ALBUM("object.container.album"),
    @XmlEnumValue("object.container.album.musicAlbum")
    OBJECT_CONTAINER_ALBUM_MUSIC_ALBUM("object.container.album.musicAlbum"),
    @XmlEnumValue("object.container.album.photoAlbum")
    OBJECT_CONTAINER_ALBUM_PHOTO_ALBUM("object.container.album.photoAlbum"),
    @XmlEnumValue("object.container.genre")
    OBJECT_CONTAINER_GENRE("object.container.genre"),
    @XmlEnumValue("object.container.genre.musicGenre")
    OBJECT_CONTAINER_GENRE_MUSIC_GENRE("object.container.genre.musicGenre"),
    @XmlEnumValue("object.container.genre.movieGenre")
    OBJECT_CONTAINER_GENRE_MOVIE_GENRE("object.container.genre.movieGenre"),
    @XmlEnumValue("object.container.channelGroup")
    OBJECT_CONTAINER_CHANNEL_GROUP("object.container.channelGroup"),
    @XmlEnumValue("object.container.channelGroup.audioChannelGroup")
    OBJECT_CONTAINER_CHANNEL_GROUP_AUDIO_CHANNEL_GROUP("object.container.channelGroup.audioChannelGroup"),
    @XmlEnumValue("object.container.channelGroup.videoChannelGroup")
    OBJECT_CONTAINER_CHANNEL_GROUP_VIDEO_CHANNEL_GROUP("object.container.channelGroup.videoChannelGroup"),
    @XmlEnumValue("object.container.epgContainer")
    OBJECT_CONTAINER_EPG_CONTAINER("object.container.epgContainer"),
    @XmlEnumValue("object.container.storageSystem")
    OBJECT_CONTAINER_STORAGE_SYSTEM("object.container.storageSystem"),
    @XmlEnumValue("object.container.storageVolume")
    OBJECT_CONTAINER_STORAGE_VOLUME("object.container.storageVolume"),
    @XmlEnumValue("object.container.storageFolder")
    OBJECT_CONTAINER_STORAGE_FOLDER("object.container.storageFolder"),
    @XmlEnumValue("object.container.bookmarkFolder")
    OBJECT_CONTAINER_BOOKMARK_FOLDER("object.container.bookmarkFolder");
    private final String value;

    ClassNameWcType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClassNameWcType fromValue(String v) {
        for (ClassNameWcType c: ClassNameWcType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
