//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//


package org.medee.playground.upnp.didllite.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				'container' element may contain any number of
 * 				1. Dublin Core,
 * 				2. upnp,
 * 				3. res,
 * 				4. ref,
 * 				5 item,
 * 				6. container and
 * 				7. desc elements.
 * 				In all cases, the first element in each container child
 * 				element sequence is required to be "dc:title".
 * 				A 'upnp:class' element must also appear under container.
 * 				container is required to specify a value for the 'id' and
 * 				'parentID' attributes.
 * 				container is also required to specify a value for the
 * 				'restricted' attribute (true, false, 1, 0).
 * 				When restricted="true", the ability to change or delete the
 * 				container is restricted.
 * 				Optional container element attributes are 'childCount', and 
 * 				'searchable'.
 * 			
 * 
 * <p>Java class for container.type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="container.type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://purl.org/dc/elements/1.1/}title"/>
 *         &lt;group ref="{urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/}allowed-under-container" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;group ref="{urn:schemas-upnp-org:metadata-1-0/upnp/}class.group"/>
 *         &lt;group ref="{urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/}allowed-under-container" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/}commonAttrs-item-container.group"/>
 *       &lt;attribute name="searchable" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="childCount" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "container.type", namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", propOrder = {
    "title",
    "allowedUnderContainer",
    "clazz",
    "allowedUnderContainerBis"
})
public class ContainerType {

    @XmlElement(namespace = "http://purl.org/dc/elements/1.1/", required = true)
    protected ElementType title;
    @XmlElementRefs({
        @XmlElementRef(name = "radioCallSign", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "actor", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "radioStationID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dateTimeRange", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "seriesID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "serviceProvider", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "director", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "channelName", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storageUsed", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "scheduledEndTime", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "recordedStartDateTime", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "res", namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "producer", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "description", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "containerUpdateID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "searchClass", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "writeStatus", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "price", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "signalLocked", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "userAnnotation", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "channelID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "date", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "callSign", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "desc", namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "originalTrackNumber", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "createClass", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rating", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "relation", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "srsRecordScheduleID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "payPerView", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "language", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "bookmarkedObjectID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "publisher", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "lyricsURI", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "lastPlaybackTime", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "stateVariableCollection", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "srsRecordTaskID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "seriesTitle", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "creator", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "foreignMetadata", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "episodeNumber", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "item", namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "longDescription", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "recordedDuration", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "genre", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "programTitle", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rights", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "radioBand", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "artistDiscographyURI", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "scheduledDuration", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "bookmarkID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "album", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storageMaxPartition", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DVDRegionCode", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "artist", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tuned", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "playbackCount", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "epgProviderName", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rights", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "lastPlaybackPosition", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "episodeType", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "networkAffiliation", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "channelNr", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "programCode", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "albumArtURI", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "toc", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "episodeCount", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "recordedDayOfWeek", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storageMedium", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storageFree", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "container", namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storageTotal", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "deviceUDN", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "objectUpdateID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "scheduledStartTime", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "contributor", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "icon", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "playlist", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "author", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "channelGroupName", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "recordable", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "signalStrength", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "region", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "programID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "totalDeletedChildCount", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> allowedUnderContainer;
    @XmlElement(name = "class", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", required = true)
    protected ClassType clazz;
    @XmlElementRefs({
        @XmlElementRef(name = "actor", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rights", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "scheduledEndTime", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "channelName", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storageFree", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "episodeCount", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "toc", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "dateTimeRange", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "icon", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "radioStationID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "lastPlaybackPosition", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "radioBand", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "bookmarkedObjectID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "res", namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storageMaxPartition", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "region", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "description", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "programCode", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "foreignMetadata", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "channelGroupName", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "createClass", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "artistDiscographyURI", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "DVDRegionCode", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "author", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "recordedDuration", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "artist", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "totalDeletedChildCount", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "item", namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "channelNr", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "date", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "recordable", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "desc", namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "originalTrackNumber", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "tuned", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "programID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rating", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "playlist", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "relation", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "programTitle", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "searchClass", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "genre", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "containerUpdateID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "language", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "publisher", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storageMedium", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "epgProviderName", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "director", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "signalLocked", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "writeStatus", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "price", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "lyricsURI", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "serviceProvider", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "creator", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "channelID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "episodeNumber", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "scheduledStartTime", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "radioCallSign", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "deviceUDN", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "rights", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "producer", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "signalStrength", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "bookmarkID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storageUsed", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "objectUpdateID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "srsRecordScheduleID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "album", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "recordedDayOfWeek", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "recordedStartDateTime", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "networkAffiliation", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "scheduledDuration", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "callSign", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "payPerView", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "playbackCount", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "longDescription", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "lastPlaybackTime", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "userAnnotation", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "contributor", namespace = "http://purl.org/dc/elements/1.1/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "srsRecordTaskID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "seriesID", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "container", namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "storageTotal", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "episodeType", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "albumArtURI", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "seriesTitle", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "stateVariableCollection", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> allowedUnderContainerBis;
    @XmlAttribute(name = "searchable")
    protected Boolean searchable;
    @XmlAttribute(name = "childCount")
    @XmlSchemaType(name = "unsignedInt")
    protected Long childCount;
    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "parentID", required = true)
    protected String parentID;
    @XmlAttribute(name = "restricted", required = true)
    protected boolean restricted;
    @XmlAttribute(name = "neverPlayable")
    protected Boolean neverPlayable;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link ElementType }
     *     
     */
    public ElementType getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElementType }
     *     
     */
    public void setTitle(ElementType value) {
        this.title = value;
    }

    /**
     * Gets the value of the allowedUnderContainer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowedUnderContainer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowedUnderContainer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link PersonWithRoleType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifiedDateTimeRange }{@code >}
     * {@link JAXBElement }{@code <}{@link ProgramIDType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifiedDateTimeISO8601 }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifiedDateTime }{@code >}
     * {@link JAXBElement }{@code <}{@link ResType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link SearchClassType }{@code >}
     * {@link JAXBElement }{@code <}{@link StatusType }{@code >}
     * {@link JAXBElement }{@code <}{@link PriceType }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link ChannelIDType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link DescType }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link SearchClassType }{@code >}
     * {@link JAXBElement }{@code <}{@link RatingType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifiedDateTime }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link StateVariableCollectionType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ForeignMetadataType }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ItemType }{@code >}
     * {@link JAXBElement }{@code <}{@link GenreType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link PersonWithRoleType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ProgramCodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link DayOfWeekEnLen3 }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link ContainerType }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link DeviceUDNType }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifiedDateTimeISO8601 }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link PersonWithRoleType }{@code >}
     * {@link JAXBElement }{@code <}{@link ChannelGroupNameType }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ProgramIDType }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getAllowedUnderContainer() {
        if (allowedUnderContainer == null) {
            allowedUnderContainer = new ArrayList<JAXBElement<?>>();
        }
        return this.allowedUnderContainer;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link ClassType }
     *     
     */
    public ClassType getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassType }
     *     
     */
    public void setClazz(ClassType value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the allowedUnderContainerBis property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowedUnderContainerBis property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowedUnderContainerBis().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link PersonWithRoleType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifiedDateTimeISO8601 }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifiedDateTimeRange }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ResType }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ProgramCodeType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ForeignMetadataType }{@code >}
     * {@link JAXBElement }{@code <}{@link SearchClassType }{@code >}
     * {@link JAXBElement }{@code <}{@link ChannelGroupNameType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link PersonWithRoleType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link PersonWithRoleType }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link DescType }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link ItemType }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link ProgramIDType }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link RatingType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link GenreType }{@code >}
     * {@link JAXBElement }{@code <}{@link SearchClassType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link StatusType }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link PriceType }{@code >}
     * {@link JAXBElement }{@code <}{@link ChannelIDType }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifiedDateTimeISO8601 }{@code >}
     * {@link JAXBElement }{@code <}{@link DeviceUDNType }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifiedDateTime }{@code >}
     * {@link JAXBElement }{@code <}{@link DayOfWeekEnLen3 }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Boolean }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link QualifiedDateTime }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link ElementType }{@code >}
     * {@link JAXBElement }{@code <}{@link ProgramIDType }{@code >}
     * {@link JAXBElement }{@code <}{@link ContainerType }{@code >}
     * {@link JAXBElement }{@code <}{@link Long }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link StateVariableCollectionType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getAllowedUnderContainerBis() {
        if (allowedUnderContainerBis == null) {
            allowedUnderContainerBis = new ArrayList<JAXBElement<?>>();
        }
        return this.allowedUnderContainerBis;
    }

    /**
     * Gets the value of the searchable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSearchable() {
        return searchable;
    }

    /**
     * Sets the value of the searchable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSearchable(Boolean value) {
        this.searchable = value;
    }

    /**
     * Gets the value of the childCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getChildCount() {
        return childCount;
    }

    /**
     * Sets the value of the childCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setChildCount(Long value) {
        this.childCount = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the parentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentID() {
        return parentID;
    }

    /**
     * Sets the value of the parentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentID(String value) {
        this.parentID = value;
    }

    /**
     * Gets the value of the restricted property.
     * 
     */
    public boolean isRestricted() {
        return restricted;
    }

    /**
     * Sets the value of the restricted property.
     * 
     */
    public void setRestricted(boolean value) {
        this.restricted = value;
    }

    /**
     * Gets the value of the neverPlayable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNeverPlayable() {
        return neverPlayable;
    }

    /**
     * Sets the value of the neverPlayable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNeverPlayable(Boolean value) {
        this.neverPlayable = value;
    }

}
