//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//


package org.medee.playground.upnp.didllite.jaxb;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * 
 * 				WC-defined structure for the Foreign Metadata property.
 * 			
 * 
 * <p>Java class for foreignMetadata.type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="foreignMetadata.type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:schemas-upnp-org:metadata-1-0/upnp/}fm.elements.group"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{urn:schemas-upnp-org:metadata-1-0/upnp/}fm.attributes.group"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "foreignMetadata.type", propOrder = {
    "fmElementsWcGroup",
    "fmElementsVxGroup"
})
public class ForeignMetadataType {

    @XmlElementRefs({
        @XmlElementRef(name = "fmId", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fmClass", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fmProvider", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "fmBody", namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> fmElementsWcGroup;
    @XmlAnyElement(lax = true)
    protected List<Object> fmElementsVxGroup;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the fmElementsWcGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fmElementsWcGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFmElementsWcGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link FmElementsBodyType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getFmElementsWcGroup() {
        if (fmElementsWcGroup == null) {
            fmElementsWcGroup = new ArrayList<JAXBElement<?>>();
        }
        return this.fmElementsWcGroup;
    }

    /**
     * Gets the value of the fmElementsVxGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fmElementsVxGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFmElementsVxGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getFmElementsVxGroup() {
        if (fmElementsVxGroup == null) {
            fmElementsVxGroup = new ArrayList<Object>();
        }
        return this.fmElementsVxGroup;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
