//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//


package org.medee.playground.upnp.didllite.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.medee.playground.upnp.didllite.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Rights_QNAME = new QName("http://purl.org/dc/elements/1.1/", "rights");
    private final static QName _Relation_QNAME = new QName("http://purl.org/dc/elements/1.1/", "relation");
    private final static QName _Format_QNAME = new QName("http://purl.org/dc/elements/1.1/", "format");
    private final static QName _Date_QNAME = new QName("http://purl.org/dc/elements/1.1/", "date");
    private final static QName _Type_QNAME = new QName("http://purl.org/dc/elements/1.1/", "type");
    private final static QName _Creator_QNAME = new QName("http://purl.org/dc/elements/1.1/", "creator");
    private final static QName _Publisher_QNAME = new QName("http://purl.org/dc/elements/1.1/", "publisher");
    private final static QName _Subject_QNAME = new QName("http://purl.org/dc/elements/1.1/", "subject");
    private final static QName _DIDLLite_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", "DIDL-Lite");
    private final static QName _Language_QNAME = new QName("http://purl.org/dc/elements/1.1/", "language");
    private final static QName _Identifier_QNAME = new QName("http://purl.org/dc/elements/1.1/", "identifier");
    private final static QName _Title_QNAME = new QName("http://purl.org/dc/elements/1.1/", "title");
    private final static QName _Source_QNAME = new QName("http://purl.org/dc/elements/1.1/", "source");
    private final static QName _Coverage_QNAME = new QName("http://purl.org/dc/elements/1.1/", "coverage");
    private final static QName _Contributor_QNAME = new QName("http://purl.org/dc/elements/1.1/", "contributor");
    private final static QName _Description_QNAME = new QName("http://purl.org/dc/elements/1.1/", "description");
    private final static QName _ContainerTypeChannelID_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "channelID");
    private final static QName _ContainerTypeAlbum_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "album");
    private final static QName _ContainerTypeRadioBand_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "radioBand");
    private final static QName _ContainerTypeCreateClass_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "createClass");
    private final static QName _ContainerTypeContainer_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", "container");
    private final static QName _ContainerTypePlaybackCount_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "playbackCount");
    private final static QName _ContainerTypeScheduledDuration_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "scheduledDuration");
    private final static QName _ContainerTypeGenre_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "genre");
    private final static QName _ContainerTypeEpisodeNumber_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "episodeNumber");
    private final static QName _ContainerTypeScheduledEndTime_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "scheduledEndTime");
    private final static QName _ContainerTypeActor_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "actor");
    private final static QName _ContainerTypeDVDRegionCode_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "DVDRegionCode");
    private final static QName _ContainerTypeDateTimeRange_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "dateTimeRange");
    private final static QName _ContainerTypeRights_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "rights");
    private final static QName _ContainerTypeRecordedDuration_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "recordedDuration");
    private final static QName _ContainerTypeNetworkAffiliation_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "networkAffiliation");
    private final static QName _ContainerTypeSignalLocked_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "signalLocked");
    private final static QName _ContainerTypeServiceProvider_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "serviceProvider");
    private final static QName _ContainerTypeScheduledStartTime_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "scheduledStartTime");
    private final static QName _ContainerTypeLongDescription_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "longDescription");
    private final static QName _ContainerTypeArtistDiscographyURI_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "artistDiscographyURI");
    private final static QName _ContainerTypeStorageTotal_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "storageTotal");
    private final static QName _ContainerTypeRadioStationID_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "radioStationID");
    private final static QName _ContainerTypeSignalStrength_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "signalStrength");
    private final static QName _ContainerTypeOriginalTrackNumber_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "originalTrackNumber");
    private final static QName _ContainerTypeDirector_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "director");
    private final static QName _ContainerTypeLastPlaybackPosition_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "lastPlaybackPosition");
    private final static QName _ContainerTypeUserAnnotation_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "userAnnotation");
    private final static QName _ContainerTypeBookmarkedObjectID_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "bookmarkedObjectID");
    private final static QName _ContainerTypeDeviceUDN_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "deviceUDN");
    private final static QName _ContainerTypePrice_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "price");
    private final static QName _ContainerTypeWriteStatus_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "writeStatus");
    private final static QName _ContainerTypeRecordedDayOfWeek_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "recordedDayOfWeek");
    private final static QName _ContainerTypeSearchClass_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "searchClass");
    private final static QName _ContainerTypeStorageMaxPartition_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "storageMaxPartition");
    private final static QName _ContainerTypeEpisodeCount_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "episodeCount");
    private final static QName _ContainerTypeEpisodeType_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "episodeType");
    private final static QName _ContainerTypeToc_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "toc");
    private final static QName _ContainerTypeItem_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", "item");
    private final static QName _ContainerTypeRegion_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "region");
    private final static QName _ContainerTypeChannelNr_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "channelNr");
    private final static QName _ContainerTypeStorageUsed_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "storageUsed");
    private final static QName _ContainerTypeForeignMetadata_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "foreignMetadata");
    private final static QName _ContainerTypeSrsRecordTaskID_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "srsRecordTaskID");
    private final static QName _ContainerTypeProgramCode_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "programCode");
    private final static QName _ContainerTypeBookmarkID_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "bookmarkID");
    private final static QName _ContainerTypeProgramTitle_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "programTitle");
    private final static QName _ContainerTypeCallSign_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "callSign");
    private final static QName _ContainerTypeTuned_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "tuned");
    private final static QName _ContainerTypeRecordable_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "recordable");
    private final static QName _ContainerTypeContainerUpdateID_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "containerUpdateID");
    private final static QName _ContainerTypeAuthor_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "author");
    private final static QName _ContainerTypeSeriesID_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "seriesID");
    private final static QName _ContainerTypeStateVariableCollection_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "stateVariableCollection");
    private final static QName _ContainerTypePlaylist_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "playlist");
    private final static QName _ContainerTypeArtist_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "artist");
    private final static QName _ContainerTypePayPerView_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "payPerView");
    private final static QName _ContainerTypeSrsRecordScheduleID_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "srsRecordScheduleID");
    private final static QName _ContainerTypeAlbumArtURI_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "albumArtURI");
    private final static QName _ContainerTypeChannelGroupName_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "channelGroupName");
    private final static QName _ContainerTypeRecordedStartDateTime_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "recordedStartDateTime");
    private final static QName _ContainerTypeChannelName_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "channelName");
    private final static QName _ContainerTypeIcon_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "icon");
    private final static QName _ContainerTypeTotalDeletedChildCount_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "totalDeletedChildCount");
    private final static QName _ContainerTypeSeriesTitle_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "seriesTitle");
    private final static QName _ContainerTypeRes_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", "res");
    private final static QName _ContainerTypeStorageFree_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "storageFree");
    private final static QName _ContainerTypeLyricsURI_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "lyricsURI");
    private final static QName _ContainerTypeDesc_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", "desc");
    private final static QName _ContainerTypeRadioCallSign_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "radioCallSign");
    private final static QName _ContainerTypeObjectUpdateID_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "objectUpdateID");
    private final static QName _ContainerTypeProgramID_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "programID");
    private final static QName _ContainerTypeLastPlaybackTime_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "lastPlaybackTime");
    private final static QName _ContainerTypeEpgProviderName_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "epgProviderName");
    private final static QName _ContainerTypeRating_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "rating");
    private final static QName _ContainerTypeProducer_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "producer");
    private final static QName _ContainerTypeStorageMedium_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "storageMedium");
    private final static QName _ForeignMetadataTypeFmProvider_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "fmProvider");
    private final static QName _ForeignMetadataTypeFmId_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "fmId");
    private final static QName _ForeignMetadataTypeFmBody_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "fmBody");
    private final static QName _ForeignMetadataTypeFmClass_QNAME = new QName("urn:schemas-upnp-org:metadata-1-0/upnp/", "fmClass");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.medee.playground.upnp.didllite.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FmElementsBodyEmbeddedStringType }
     * 
     */
    public FmElementsBodyEmbeddedStringType createFmElementsBodyEmbeddedStringType() {
        return new FmElementsBodyEmbeddedStringType();
    }

    /**
     * Create an instance of {@link ContainerType }
     * 
     */
    public ContainerType createContainerType() {
        return new ContainerType();
    }

    /**
     * Create an instance of {@link QualifiedDateTimeISO8601AndUsage }
     * 
     */
    public QualifiedDateTimeISO8601AndUsage createQualifiedDateTimeISO8601AndUsage() {
        return new QualifiedDateTimeISO8601AndUsage();
    }

    /**
     * Create an instance of {@link QualifiedDateTimeISO8601 }
     * 
     */
    public QualifiedDateTimeISO8601 createQualifiedDateTimeISO8601() {
        return new QualifiedDateTimeISO8601();
    }

    /**
     * Create an instance of {@link GenreType }
     * 
     */
    public GenreType createGenreType() {
        return new GenreType();
    }

    /**
     * Create an instance of {@link FmElementsBodyType }
     * 
     */
    public FmElementsBodyType createFmElementsBodyType() {
        return new FmElementsBodyType();
    }

    /**
     * Create an instance of {@link DeviceUDNType }
     * 
     */
    public DeviceUDNType createDeviceUDNType() {
        return new DeviceUDNType();
    }

    /**
     * Create an instance of {@link DescType }
     * 
     */
    public DescType createDescType() {
        return new DescType();
    }

    /**
     * Create an instance of {@link SearchClassType }
     * 
     */
    public SearchClassType createSearchClassType() {
        return new SearchClassType();
    }

    /**
     * Create an instance of {@link RatingType }
     * 
     */
    public RatingType createRatingType() {
        return new RatingType();
    }

    /**
     * Create an instance of {@link QualifiedDateTime }
     * 
     */
    public QualifiedDateTime createQualifiedDateTime() {
        return new QualifiedDateTime();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link ForeignMetadataType }
     * 
     */
    public ForeignMetadataType createForeignMetadataType() {
        return new ForeignMetadataType();
    }

    /**
     * Create an instance of {@link ChannelIDType }
     * 
     */
    public ChannelIDType createChannelIDType() {
        return new ChannelIDType();
    }

    /**
     * Create an instance of {@link RootType }
     * 
     */
    public RootType createRootType() {
        return new RootType();
    }

    /**
     * Create an instance of {@link ChannelGroupNameType }
     * 
     */
    public ChannelGroupNameType createChannelGroupNameType() {
        return new ChannelGroupNameType();
    }

    /**
     * Create an instance of {@link ResType }
     * 
     */
    public ResType createResType() {
        return new ResType();
    }

    /**
     * Create an instance of {@link FmElementsBodyEmbeddedXMLType }
     * 
     */
    public FmElementsBodyEmbeddedXMLType createFmElementsBodyEmbeddedXMLType() {
        return new FmElementsBodyEmbeddedXMLType();
    }

    /**
     * Create an instance of {@link QualifiedDCDate }
     * 
     */
    public QualifiedDCDate createQualifiedDCDate() {
        return new QualifiedDCDate();
    }

    /**
     * Create an instance of {@link ProgramCodeType }
     * 
     */
    public ProgramCodeType createProgramCodeType() {
        return new ProgramCodeType();
    }

    /**
     * Create an instance of {@link ProgramIDType }
     * 
     */
    public ProgramIDType createProgramIDType() {
        return new ProgramIDType();
    }

    /**
     * Create an instance of {@link QualifiedDateTimeRange }
     * 
     */
    public QualifiedDateTimeRange createQualifiedDateTimeRange() {
        return new QualifiedDateTimeRange();
    }

    /**
     * Create an instance of {@link StateVariableCollectionType }
     * 
     */
    public StateVariableCollectionType createStateVariableCollectionType() {
        return new StateVariableCollectionType();
    }

    /**
     * Create an instance of {@link ElementType }
     * 
     */
    public ElementType createElementType() {
        return new ElementType();
    }

    /**
     * Create an instance of {@link ClassType }
     * 
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link PersonWithRoleType }
     * 
     */
    public PersonWithRoleType createPersonWithRoleType() {
        return new PersonWithRoleType();
    }

    /**
     * Create an instance of {@link StorageMediumType }
     * 
     */
    public StorageMediumType createStorageMediumType() {
        return new StorageMediumType();
    }

    /**
     * Create an instance of {@link FmElementsBodyUriType }
     * 
     */
    public FmElementsBodyUriType createFmElementsBodyUriType() {
        return new FmElementsBodyUriType();
    }

    /**
     * Create an instance of {@link PriceType }
     * 
     */
    public PriceType createPriceType() {
        return new PriceType();
    }

    /**
     * Create an instance of {@link StateVariableType }
     * 
     */
    public StateVariableType createStateVariableType() {
        return new StateVariableType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "rights")
    public JAXBElement<ElementType> createRights(ElementType value) {
        return new JAXBElement<ElementType>(_Rights_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "relation")
    public JAXBElement<ElementType> createRelation(ElementType value) {
        return new JAXBElement<ElementType>(_Relation_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "format")
    public JAXBElement<ElementType> createFormat(ElementType value) {
        return new JAXBElement<ElementType>(_Format_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "date")
    public JAXBElement<ElementType> createDate(ElementType value) {
        return new JAXBElement<ElementType>(_Date_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "type")
    public JAXBElement<ElementType> createType(ElementType value) {
        return new JAXBElement<ElementType>(_Type_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "creator")
    public JAXBElement<ElementType> createCreator(ElementType value) {
        return new JAXBElement<ElementType>(_Creator_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "publisher")
    public JAXBElement<ElementType> createPublisher(ElementType value) {
        return new JAXBElement<ElementType>(_Publisher_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "subject")
    public JAXBElement<ElementType> createSubject(ElementType value) {
        return new JAXBElement<ElementType>(_Subject_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RootType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", name = "DIDL-Lite")
    public JAXBElement<RootType> createDIDLLite(RootType value) {
        return new JAXBElement<RootType>(_DIDLLite_QNAME, RootType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "language")
    public JAXBElement<ElementType> createLanguage(ElementType value) {
        return new JAXBElement<ElementType>(_Language_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "identifier")
    public JAXBElement<ElementType> createIdentifier(ElementType value) {
        return new JAXBElement<ElementType>(_Identifier_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "title")
    public JAXBElement<ElementType> createTitle(ElementType value) {
        return new JAXBElement<ElementType>(_Title_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "source")
    public JAXBElement<ElementType> createSource(ElementType value) {
        return new JAXBElement<ElementType>(_Source_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "coverage")
    public JAXBElement<ElementType> createCoverage(ElementType value) {
        return new JAXBElement<ElementType>(_Coverage_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "contributor")
    public JAXBElement<ElementType> createContributor(ElementType value) {
        return new JAXBElement<ElementType>(_Contributor_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://purl.org/dc/elements/1.1/", name = "description")
    public JAXBElement<ElementType> createDescription(ElementType value) {
        return new JAXBElement<ElementType>(_Description_QNAME, ElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChannelIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "channelID", scope = ContainerType.class)
    public JAXBElement<ChannelIDType> createContainerTypeChannelID(ChannelIDType value) {
        return new JAXBElement<ChannelIDType>(_ContainerTypeChannelID_QNAME, ChannelIDType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "album", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeAlbum(String value) {
        return new JAXBElement<String>(_ContainerTypeAlbum_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "radioBand", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeRadioBand(String value) {
        return new JAXBElement<String>(_ContainerTypeRadioBand_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "createClass", scope = ContainerType.class)
    public JAXBElement<SearchClassType> createContainerTypeCreateClass(SearchClassType value) {
        return new JAXBElement<SearchClassType>(_ContainerTypeCreateClass_QNAME, SearchClassType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContainerType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", name = "container", scope = ContainerType.class)
    public JAXBElement<ContainerType> createContainerTypeContainer(ContainerType value) {
        return new JAXBElement<ContainerType>(_ContainerTypeContainer_QNAME, ContainerType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "playbackCount", scope = ContainerType.class)
    public JAXBElement<Integer> createContainerTypePlaybackCount(Integer value) {
        return new JAXBElement<Integer>(_ContainerTypePlaybackCount_QNAME, Integer.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "scheduledDuration", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeScheduledDuration(String value) {
        return new JAXBElement<String>(_ContainerTypeScheduledDuration_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenreType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "genre", scope = ContainerType.class)
    public JAXBElement<GenreType> createContainerTypeGenre(GenreType value) {
        return new JAXBElement<GenreType>(_ContainerTypeGenre_QNAME, GenreType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "episodeNumber", scope = ContainerType.class)
    public JAXBElement<Long> createContainerTypeEpisodeNumber(Long value) {
        return new JAXBElement<Long>(_ContainerTypeEpisodeNumber_QNAME, Long.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifiedDateTimeISO8601 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "scheduledEndTime", scope = ContainerType.class)
    public JAXBElement<QualifiedDateTimeISO8601> createContainerTypeScheduledEndTime(QualifiedDateTimeISO8601 value) {
        return new JAXBElement<QualifiedDateTimeISO8601>(_ContainerTypeScheduledEndTime_QNAME, QualifiedDateTimeISO8601 .class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonWithRoleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "actor", scope = ContainerType.class)
    public JAXBElement<PersonWithRoleType> createContainerTypeActor(PersonWithRoleType value) {
        return new JAXBElement<PersonWithRoleType>(_ContainerTypeActor_QNAME, PersonWithRoleType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "DVDRegionCode", scope = ContainerType.class)
    public JAXBElement<Integer> createContainerTypeDVDRegionCode(Integer value) {
        return new JAXBElement<Integer>(_ContainerTypeDVDRegionCode_QNAME, Integer.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifiedDateTimeRange }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "dateTimeRange", scope = ContainerType.class)
    public JAXBElement<QualifiedDateTimeRange> createContainerTypeDateTimeRange(QualifiedDateTimeRange value) {
        return new JAXBElement<QualifiedDateTimeRange>(_ContainerTypeDateTimeRange_QNAME, QualifiedDateTimeRange.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "rights", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeRights(String value) {
        return new JAXBElement<String>(_ContainerTypeRights_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "recordedDuration", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeRecordedDuration(String value) {
        return new JAXBElement<String>(_ContainerTypeRecordedDuration_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "networkAffiliation", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeNetworkAffiliation(String value) {
        return new JAXBElement<String>(_ContainerTypeNetworkAffiliation_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "signalLocked", scope = ContainerType.class)
    public JAXBElement<Boolean> createContainerTypeSignalLocked(Boolean value) {
        return new JAXBElement<Boolean>(_ContainerTypeSignalLocked_QNAME, Boolean.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "serviceProvider", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeServiceProvider(String value) {
        return new JAXBElement<String>(_ContainerTypeServiceProvider_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifiedDateTimeISO8601 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "scheduledStartTime", scope = ContainerType.class)
    public JAXBElement<QualifiedDateTimeISO8601> createContainerTypeScheduledStartTime(QualifiedDateTimeISO8601 value) {
        return new JAXBElement<QualifiedDateTimeISO8601>(_ContainerTypeScheduledStartTime_QNAME, QualifiedDateTimeISO8601 .class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "longDescription", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeLongDescription(String value) {
        return new JAXBElement<String>(_ContainerTypeLongDescription_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "artistDiscographyURI", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeArtistDiscographyURI(String value) {
        return new JAXBElement<String>(_ContainerTypeArtistDiscographyURI_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "storageTotal", scope = ContainerType.class)
    public JAXBElement<Long> createContainerTypeStorageTotal(Long value) {
        return new JAXBElement<Long>(_ContainerTypeStorageTotal_QNAME, Long.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "radioStationID", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeRadioStationID(String value) {
        return new JAXBElement<String>(_ContainerTypeRadioStationID_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "signalStrength", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeSignalStrength(String value) {
        return new JAXBElement<String>(_ContainerTypeSignalStrength_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "originalTrackNumber", scope = ContainerType.class)
    public JAXBElement<Integer> createContainerTypeOriginalTrackNumber(Integer value) {
        return new JAXBElement<Integer>(_ContainerTypeOriginalTrackNumber_QNAME, Integer.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "director", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeDirector(String value) {
        return new JAXBElement<String>(_ContainerTypeDirector_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "lastPlaybackPosition", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeLastPlaybackPosition(String value) {
        return new JAXBElement<String>(_ContainerTypeLastPlaybackPosition_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "userAnnotation", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeUserAnnotation(String value) {
        return new JAXBElement<String>(_ContainerTypeUserAnnotation_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "bookmarkedObjectID", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeBookmarkedObjectID(String value) {
        return new JAXBElement<String>(_ContainerTypeBookmarkedObjectID_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeviceUDNType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "deviceUDN", scope = ContainerType.class)
    public JAXBElement<DeviceUDNType> createContainerTypeDeviceUDN(DeviceUDNType value) {
        return new JAXBElement<DeviceUDNType>(_ContainerTypeDeviceUDN_QNAME, DeviceUDNType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PriceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "price", scope = ContainerType.class)
    public JAXBElement<PriceType> createContainerTypePrice(PriceType value) {
        return new JAXBElement<PriceType>(_ContainerTypePrice_QNAME, PriceType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "writeStatus", scope = ContainerType.class)
    public JAXBElement<StatusType> createContainerTypeWriteStatus(StatusType value) {
        return new JAXBElement<StatusType>(_ContainerTypeWriteStatus_QNAME, StatusType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DayOfWeekEnLen3 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "recordedDayOfWeek", scope = ContainerType.class)
    public JAXBElement<DayOfWeekEnLen3> createContainerTypeRecordedDayOfWeek(DayOfWeekEnLen3 value) {
        return new JAXBElement<DayOfWeekEnLen3>(_ContainerTypeRecordedDayOfWeek_QNAME, DayOfWeekEnLen3 .class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "searchClass", scope = ContainerType.class)
    public JAXBElement<SearchClassType> createContainerTypeSearchClass(SearchClassType value) {
        return new JAXBElement<SearchClassType>(_ContainerTypeSearchClass_QNAME, SearchClassType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "storageMaxPartition", scope = ContainerType.class)
    public JAXBElement<Long> createContainerTypeStorageMaxPartition(Long value) {
        return new JAXBElement<Long>(_ContainerTypeStorageMaxPartition_QNAME, Long.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "episodeCount", scope = ContainerType.class)
    public JAXBElement<Long> createContainerTypeEpisodeCount(Long value) {
        return new JAXBElement<Long>(_ContainerTypeEpisodeCount_QNAME, Long.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "episodeType", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeEpisodeType(String value) {
        return new JAXBElement<String>(_ContainerTypeEpisodeType_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "toc", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeToc(String value) {
        return new JAXBElement<String>(_ContainerTypeToc_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", name = "item", scope = ContainerType.class)
    public JAXBElement<ItemType> createContainerTypeItem(ItemType value) {
        return new JAXBElement<ItemType>(_ContainerTypeItem_QNAME, ItemType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "region", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeRegion(String value) {
        return new JAXBElement<String>(_ContainerTypeRegion_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "channelNr", scope = ContainerType.class)
    public JAXBElement<Integer> createContainerTypeChannelNr(Integer value) {
        return new JAXBElement<Integer>(_ContainerTypeChannelNr_QNAME, Integer.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "storageUsed", scope = ContainerType.class)
    public JAXBElement<Long> createContainerTypeStorageUsed(Long value) {
        return new JAXBElement<Long>(_ContainerTypeStorageUsed_QNAME, Long.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForeignMetadataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "foreignMetadata", scope = ContainerType.class)
    public JAXBElement<ForeignMetadataType> createContainerTypeForeignMetadata(ForeignMetadataType value) {
        return new JAXBElement<ForeignMetadataType>(_ContainerTypeForeignMetadata_QNAME, ForeignMetadataType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "srsRecordTaskID", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeSrsRecordTaskID(String value) {
        return new JAXBElement<String>(_ContainerTypeSrsRecordTaskID_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "programCode", scope = ContainerType.class)
    public JAXBElement<ProgramCodeType> createContainerTypeProgramCode(ProgramCodeType value) {
        return new JAXBElement<ProgramCodeType>(_ContainerTypeProgramCode_QNAME, ProgramCodeType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "bookmarkID", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeBookmarkID(String value) {
        return new JAXBElement<String>(_ContainerTypeBookmarkID_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "programTitle", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeProgramTitle(String value) {
        return new JAXBElement<String>(_ContainerTypeProgramTitle_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "callSign", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeCallSign(String value) {
        return new JAXBElement<String>(_ContainerTypeCallSign_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "tuned", scope = ContainerType.class)
    public JAXBElement<Boolean> createContainerTypeTuned(Boolean value) {
        return new JAXBElement<Boolean>(_ContainerTypeTuned_QNAME, Boolean.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "recordable", scope = ContainerType.class)
    public JAXBElement<Boolean> createContainerTypeRecordable(Boolean value) {
        return new JAXBElement<Boolean>(_ContainerTypeRecordable_QNAME, Boolean.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "containerUpdateID", scope = ContainerType.class)
    public JAXBElement<Long> createContainerTypeContainerUpdateID(Long value) {
        return new JAXBElement<Long>(_ContainerTypeContainerUpdateID_QNAME, Long.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonWithRoleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "author", scope = ContainerType.class)
    public JAXBElement<PersonWithRoleType> createContainerTypeAuthor(PersonWithRoleType value) {
        return new JAXBElement<PersonWithRoleType>(_ContainerTypeAuthor_QNAME, PersonWithRoleType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "seriesID", scope = ContainerType.class)
    public JAXBElement<ProgramIDType> createContainerTypeSeriesID(ProgramIDType value) {
        return new JAXBElement<ProgramIDType>(_ContainerTypeSeriesID_QNAME, ProgramIDType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateVariableCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "stateVariableCollection", scope = ContainerType.class)
    public JAXBElement<StateVariableCollectionType> createContainerTypeStateVariableCollection(StateVariableCollectionType value) {
        return new JAXBElement<StateVariableCollectionType>(_ContainerTypeStateVariableCollection_QNAME, StateVariableCollectionType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "playlist", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypePlaylist(String value) {
        return new JAXBElement<String>(_ContainerTypePlaylist_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonWithRoleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "artist", scope = ContainerType.class)
    public JAXBElement<PersonWithRoleType> createContainerTypeArtist(PersonWithRoleType value) {
        return new JAXBElement<PersonWithRoleType>(_ContainerTypeArtist_QNAME, PersonWithRoleType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "payPerView", scope = ContainerType.class)
    public JAXBElement<Boolean> createContainerTypePayPerView(Boolean value) {
        return new JAXBElement<Boolean>(_ContainerTypePayPerView_QNAME, Boolean.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "srsRecordScheduleID", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeSrsRecordScheduleID(String value) {
        return new JAXBElement<String>(_ContainerTypeSrsRecordScheduleID_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "albumArtURI", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeAlbumArtURI(String value) {
        return new JAXBElement<String>(_ContainerTypeAlbumArtURI_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChannelGroupNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "channelGroupName", scope = ContainerType.class)
    public JAXBElement<ChannelGroupNameType> createContainerTypeChannelGroupName(ChannelGroupNameType value) {
        return new JAXBElement<ChannelGroupNameType>(_ContainerTypeChannelGroupName_QNAME, ChannelGroupNameType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifiedDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "recordedStartDateTime", scope = ContainerType.class)
    public JAXBElement<QualifiedDateTime> createContainerTypeRecordedStartDateTime(QualifiedDateTime value) {
        return new JAXBElement<QualifiedDateTime>(_ContainerTypeRecordedStartDateTime_QNAME, QualifiedDateTime.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "channelName", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeChannelName(String value) {
        return new JAXBElement<String>(_ContainerTypeChannelName_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "icon", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeIcon(String value) {
        return new JAXBElement<String>(_ContainerTypeIcon_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "totalDeletedChildCount", scope = ContainerType.class)
    public JAXBElement<Long> createContainerTypeTotalDeletedChildCount(Long value) {
        return new JAXBElement<Long>(_ContainerTypeTotalDeletedChildCount_QNAME, Long.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "seriesTitle", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeSeriesTitle(String value) {
        return new JAXBElement<String>(_ContainerTypeSeriesTitle_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", name = "res", scope = ContainerType.class)
    public JAXBElement<ResType> createContainerTypeRes(ResType value) {
        return new JAXBElement<ResType>(_ContainerTypeRes_QNAME, ResType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "storageFree", scope = ContainerType.class)
    public JAXBElement<Long> createContainerTypeStorageFree(Long value) {
        return new JAXBElement<Long>(_ContainerTypeStorageFree_QNAME, Long.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "lyricsURI", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeLyricsURI(String value) {
        return new JAXBElement<String>(_ContainerTypeLyricsURI_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", name = "desc", scope = ContainerType.class)
    public JAXBElement<DescType> createContainerTypeDesc(DescType value) {
        return new JAXBElement<DescType>(_ContainerTypeDesc_QNAME, DescType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "radioCallSign", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeRadioCallSign(String value) {
        return new JAXBElement<String>(_ContainerTypeRadioCallSign_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "objectUpdateID", scope = ContainerType.class)
    public JAXBElement<Long> createContainerTypeObjectUpdateID(Long value) {
        return new JAXBElement<Long>(_ContainerTypeObjectUpdateID_QNAME, Long.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "programID", scope = ContainerType.class)
    public JAXBElement<ProgramIDType> createContainerTypeProgramID(ProgramIDType value) {
        return new JAXBElement<ProgramIDType>(_ContainerTypeProgramID_QNAME, ProgramIDType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifiedDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "lastPlaybackTime", scope = ContainerType.class)
    public JAXBElement<QualifiedDateTime> createContainerTypeLastPlaybackTime(QualifiedDateTime value) {
        return new JAXBElement<QualifiedDateTime>(_ContainerTypeLastPlaybackTime_QNAME, QualifiedDateTime.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "epgProviderName", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeEpgProviderName(String value) {
        return new JAXBElement<String>(_ContainerTypeEpgProviderName_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RatingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "rating", scope = ContainerType.class)
    public JAXBElement<RatingType> createContainerTypeRating(RatingType value) {
        return new JAXBElement<RatingType>(_ContainerTypeRating_QNAME, RatingType.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "producer", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeProducer(String value) {
        return new JAXBElement<String>(_ContainerTypeProducer_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "storageMedium", scope = ContainerType.class)
    public JAXBElement<String> createContainerTypeStorageMedium(String value) {
        return new JAXBElement<String>(_ContainerTypeStorageMedium_QNAME, String.class, ContainerType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "album", scope = ItemType.class)
    public JAXBElement<String> createItemTypeAlbum(String value) {
        return new JAXBElement<String>(_ContainerTypeAlbum_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChannelIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "channelID", scope = ItemType.class)
    public JAXBElement<ChannelIDType> createItemTypeChannelID(ChannelIDType value) {
        return new JAXBElement<ChannelIDType>(_ContainerTypeChannelID_QNAME, ChannelIDType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "radioBand", scope = ItemType.class)
    public JAXBElement<String> createItemTypeRadioBand(String value) {
        return new JAXBElement<String>(_ContainerTypeRadioBand_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "createClass", scope = ItemType.class)
    public JAXBElement<SearchClassType> createItemTypeCreateClass(SearchClassType value) {
        return new JAXBElement<SearchClassType>(_ContainerTypeCreateClass_QNAME, SearchClassType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "playbackCount", scope = ItemType.class)
    public JAXBElement<Integer> createItemTypePlaybackCount(Integer value) {
        return new JAXBElement<Integer>(_ContainerTypePlaybackCount_QNAME, Integer.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "scheduledDuration", scope = ItemType.class)
    public JAXBElement<String> createItemTypeScheduledDuration(String value) {
        return new JAXBElement<String>(_ContainerTypeScheduledDuration_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenreType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "genre", scope = ItemType.class)
    public JAXBElement<GenreType> createItemTypeGenre(GenreType value) {
        return new JAXBElement<GenreType>(_ContainerTypeGenre_QNAME, GenreType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "episodeNumber", scope = ItemType.class)
    public JAXBElement<Long> createItemTypeEpisodeNumber(Long value) {
        return new JAXBElement<Long>(_ContainerTypeEpisodeNumber_QNAME, Long.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifiedDateTimeISO8601 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "scheduledEndTime", scope = ItemType.class)
    public JAXBElement<QualifiedDateTimeISO8601> createItemTypeScheduledEndTime(QualifiedDateTimeISO8601 value) {
        return new JAXBElement<QualifiedDateTimeISO8601>(_ContainerTypeScheduledEndTime_QNAME, QualifiedDateTimeISO8601 .class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonWithRoleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "actor", scope = ItemType.class)
    public JAXBElement<PersonWithRoleType> createItemTypeActor(PersonWithRoleType value) {
        return new JAXBElement<PersonWithRoleType>(_ContainerTypeActor_QNAME, PersonWithRoleType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "DVDRegionCode", scope = ItemType.class)
    public JAXBElement<Integer> createItemTypeDVDRegionCode(Integer value) {
        return new JAXBElement<Integer>(_ContainerTypeDVDRegionCode_QNAME, Integer.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifiedDateTimeRange }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "dateTimeRange", scope = ItemType.class)
    public JAXBElement<QualifiedDateTimeRange> createItemTypeDateTimeRange(QualifiedDateTimeRange value) {
        return new JAXBElement<QualifiedDateTimeRange>(_ContainerTypeDateTimeRange_QNAME, QualifiedDateTimeRange.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "rights", scope = ItemType.class)
    public JAXBElement<String> createItemTypeRights(String value) {
        return new JAXBElement<String>(_ContainerTypeRights_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "recordedDuration", scope = ItemType.class)
    public JAXBElement<String> createItemTypeRecordedDuration(String value) {
        return new JAXBElement<String>(_ContainerTypeRecordedDuration_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "networkAffiliation", scope = ItemType.class)
    public JAXBElement<String> createItemTypeNetworkAffiliation(String value) {
        return new JAXBElement<String>(_ContainerTypeNetworkAffiliation_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "signalLocked", scope = ItemType.class)
    public JAXBElement<Boolean> createItemTypeSignalLocked(Boolean value) {
        return new JAXBElement<Boolean>(_ContainerTypeSignalLocked_QNAME, Boolean.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "serviceProvider", scope = ItemType.class)
    public JAXBElement<String> createItemTypeServiceProvider(String value) {
        return new JAXBElement<String>(_ContainerTypeServiceProvider_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifiedDateTimeISO8601 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "scheduledStartTime", scope = ItemType.class)
    public JAXBElement<QualifiedDateTimeISO8601> createItemTypeScheduledStartTime(QualifiedDateTimeISO8601 value) {
        return new JAXBElement<QualifiedDateTimeISO8601>(_ContainerTypeScheduledStartTime_QNAME, QualifiedDateTimeISO8601 .class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "longDescription", scope = ItemType.class)
    public JAXBElement<String> createItemTypeLongDescription(String value) {
        return new JAXBElement<String>(_ContainerTypeLongDescription_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "artistDiscographyURI", scope = ItemType.class)
    public JAXBElement<String> createItemTypeArtistDiscographyURI(String value) {
        return new JAXBElement<String>(_ContainerTypeArtistDiscographyURI_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "radioStationID", scope = ItemType.class)
    public JAXBElement<String> createItemTypeRadioStationID(String value) {
        return new JAXBElement<String>(_ContainerTypeRadioStationID_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "storageTotal", scope = ItemType.class)
    public JAXBElement<Long> createItemTypeStorageTotal(Long value) {
        return new JAXBElement<Long>(_ContainerTypeStorageTotal_QNAME, Long.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "signalStrength", scope = ItemType.class)
    public JAXBElement<String> createItemTypeSignalStrength(String value) {
        return new JAXBElement<String>(_ContainerTypeSignalStrength_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "originalTrackNumber", scope = ItemType.class)
    public JAXBElement<Integer> createItemTypeOriginalTrackNumber(Integer value) {
        return new JAXBElement<Integer>(_ContainerTypeOriginalTrackNumber_QNAME, Integer.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "director", scope = ItemType.class)
    public JAXBElement<String> createItemTypeDirector(String value) {
        return new JAXBElement<String>(_ContainerTypeDirector_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "lastPlaybackPosition", scope = ItemType.class)
    public JAXBElement<String> createItemTypeLastPlaybackPosition(String value) {
        return new JAXBElement<String>(_ContainerTypeLastPlaybackPosition_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "userAnnotation", scope = ItemType.class)
    public JAXBElement<String> createItemTypeUserAnnotation(String value) {
        return new JAXBElement<String>(_ContainerTypeUserAnnotation_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "bookmarkedObjectID", scope = ItemType.class)
    public JAXBElement<String> createItemTypeBookmarkedObjectID(String value) {
        return new JAXBElement<String>(_ContainerTypeBookmarkedObjectID_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PriceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "price", scope = ItemType.class)
    public JAXBElement<PriceType> createItemTypePrice(PriceType value) {
        return new JAXBElement<PriceType>(_ContainerTypePrice_QNAME, PriceType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeviceUDNType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "deviceUDN", scope = ItemType.class)
    public JAXBElement<DeviceUDNType> createItemTypeDeviceUDN(DeviceUDNType value) {
        return new JAXBElement<DeviceUDNType>(_ContainerTypeDeviceUDN_QNAME, DeviceUDNType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "writeStatus", scope = ItemType.class)
    public JAXBElement<StatusType> createItemTypeWriteStatus(StatusType value) {
        return new JAXBElement<StatusType>(_ContainerTypeWriteStatus_QNAME, StatusType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DayOfWeekEnLen3 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "recordedDayOfWeek", scope = ItemType.class)
    public JAXBElement<DayOfWeekEnLen3> createItemTypeRecordedDayOfWeek(DayOfWeekEnLen3 value) {
        return new JAXBElement<DayOfWeekEnLen3>(_ContainerTypeRecordedDayOfWeek_QNAME, DayOfWeekEnLen3 .class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "searchClass", scope = ItemType.class)
    public JAXBElement<SearchClassType> createItemTypeSearchClass(SearchClassType value) {
        return new JAXBElement<SearchClassType>(_ContainerTypeSearchClass_QNAME, SearchClassType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "storageMaxPartition", scope = ItemType.class)
    public JAXBElement<Long> createItemTypeStorageMaxPartition(Long value) {
        return new JAXBElement<Long>(_ContainerTypeStorageMaxPartition_QNAME, Long.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "episodeCount", scope = ItemType.class)
    public JAXBElement<Long> createItemTypeEpisodeCount(Long value) {
        return new JAXBElement<Long>(_ContainerTypeEpisodeCount_QNAME, Long.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "episodeType", scope = ItemType.class)
    public JAXBElement<String> createItemTypeEpisodeType(String value) {
        return new JAXBElement<String>(_ContainerTypeEpisodeType_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "toc", scope = ItemType.class)
    public JAXBElement<String> createItemTypeToc(String value) {
        return new JAXBElement<String>(_ContainerTypeToc_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "region", scope = ItemType.class)
    public JAXBElement<String> createItemTypeRegion(String value) {
        return new JAXBElement<String>(_ContainerTypeRegion_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "channelNr", scope = ItemType.class)
    public JAXBElement<Integer> createItemTypeChannelNr(Integer value) {
        return new JAXBElement<Integer>(_ContainerTypeChannelNr_QNAME, Integer.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "storageUsed", scope = ItemType.class)
    public JAXBElement<Long> createItemTypeStorageUsed(Long value) {
        return new JAXBElement<Long>(_ContainerTypeStorageUsed_QNAME, Long.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ForeignMetadataType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "foreignMetadata", scope = ItemType.class)
    public JAXBElement<ForeignMetadataType> createItemTypeForeignMetadata(ForeignMetadataType value) {
        return new JAXBElement<ForeignMetadataType>(_ContainerTypeForeignMetadata_QNAME, ForeignMetadataType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "srsRecordTaskID", scope = ItemType.class)
    public JAXBElement<String> createItemTypeSrsRecordTaskID(String value) {
        return new JAXBElement<String>(_ContainerTypeSrsRecordTaskID_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "bookmarkID", scope = ItemType.class)
    public JAXBElement<String> createItemTypeBookmarkID(String value) {
        return new JAXBElement<String>(_ContainerTypeBookmarkID_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramCodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "programCode", scope = ItemType.class)
    public JAXBElement<ProgramCodeType> createItemTypeProgramCode(ProgramCodeType value) {
        return new JAXBElement<ProgramCodeType>(_ContainerTypeProgramCode_QNAME, ProgramCodeType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "programTitle", scope = ItemType.class)
    public JAXBElement<String> createItemTypeProgramTitle(String value) {
        return new JAXBElement<String>(_ContainerTypeProgramTitle_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "callSign", scope = ItemType.class)
    public JAXBElement<String> createItemTypeCallSign(String value) {
        return new JAXBElement<String>(_ContainerTypeCallSign_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "tuned", scope = ItemType.class)
    public JAXBElement<Boolean> createItemTypeTuned(Boolean value) {
        return new JAXBElement<Boolean>(_ContainerTypeTuned_QNAME, Boolean.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "recordable", scope = ItemType.class)
    public JAXBElement<Boolean> createItemTypeRecordable(Boolean value) {
        return new JAXBElement<Boolean>(_ContainerTypeRecordable_QNAME, Boolean.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "containerUpdateID", scope = ItemType.class)
    public JAXBElement<Long> createItemTypeContainerUpdateID(Long value) {
        return new JAXBElement<Long>(_ContainerTypeContainerUpdateID_QNAME, Long.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonWithRoleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "author", scope = ItemType.class)
    public JAXBElement<PersonWithRoleType> createItemTypeAuthor(PersonWithRoleType value) {
        return new JAXBElement<PersonWithRoleType>(_ContainerTypeAuthor_QNAME, PersonWithRoleType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "seriesID", scope = ItemType.class)
    public JAXBElement<ProgramIDType> createItemTypeSeriesID(ProgramIDType value) {
        return new JAXBElement<ProgramIDType>(_ContainerTypeSeriesID_QNAME, ProgramIDType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateVariableCollectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "stateVariableCollection", scope = ItemType.class)
    public JAXBElement<StateVariableCollectionType> createItemTypeStateVariableCollection(StateVariableCollectionType value) {
        return new JAXBElement<StateVariableCollectionType>(_ContainerTypeStateVariableCollection_QNAME, StateVariableCollectionType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "playlist", scope = ItemType.class)
    public JAXBElement<String> createItemTypePlaylist(String value) {
        return new JAXBElement<String>(_ContainerTypePlaylist_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonWithRoleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "artist", scope = ItemType.class)
    public JAXBElement<PersonWithRoleType> createItemTypeArtist(PersonWithRoleType value) {
        return new JAXBElement<PersonWithRoleType>(_ContainerTypeArtist_QNAME, PersonWithRoleType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "payPerView", scope = ItemType.class)
    public JAXBElement<Boolean> createItemTypePayPerView(Boolean value) {
        return new JAXBElement<Boolean>(_ContainerTypePayPerView_QNAME, Boolean.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "srsRecordScheduleID", scope = ItemType.class)
    public JAXBElement<String> createItemTypeSrsRecordScheduleID(String value) {
        return new JAXBElement<String>(_ContainerTypeSrsRecordScheduleID_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "albumArtURI", scope = ItemType.class)
    public JAXBElement<String> createItemTypeAlbumArtURI(String value) {
        return new JAXBElement<String>(_ContainerTypeAlbumArtURI_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChannelGroupNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "channelGroupName", scope = ItemType.class)
    public JAXBElement<ChannelGroupNameType> createItemTypeChannelGroupName(ChannelGroupNameType value) {
        return new JAXBElement<ChannelGroupNameType>(_ContainerTypeChannelGroupName_QNAME, ChannelGroupNameType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifiedDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "recordedStartDateTime", scope = ItemType.class)
    public JAXBElement<QualifiedDateTime> createItemTypeRecordedStartDateTime(QualifiedDateTime value) {
        return new JAXBElement<QualifiedDateTime>(_ContainerTypeRecordedStartDateTime_QNAME, QualifiedDateTime.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "channelName", scope = ItemType.class)
    public JAXBElement<String> createItemTypeChannelName(String value) {
        return new JAXBElement<String>(_ContainerTypeChannelName_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "icon", scope = ItemType.class)
    public JAXBElement<String> createItemTypeIcon(String value) {
        return new JAXBElement<String>(_ContainerTypeIcon_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "totalDeletedChildCount", scope = ItemType.class)
    public JAXBElement<Long> createItemTypeTotalDeletedChildCount(Long value) {
        return new JAXBElement<Long>(_ContainerTypeTotalDeletedChildCount_QNAME, Long.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "seriesTitle", scope = ItemType.class)
    public JAXBElement<String> createItemTypeSeriesTitle(String value) {
        return new JAXBElement<String>(_ContainerTypeSeriesTitle_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", name = "res", scope = ItemType.class)
    public JAXBElement<ResType> createItemTypeRes(ResType value) {
        return new JAXBElement<ResType>(_ContainerTypeRes_QNAME, ResType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "storageFree", scope = ItemType.class)
    public JAXBElement<Long> createItemTypeStorageFree(Long value) {
        return new JAXBElement<Long>(_ContainerTypeStorageFree_QNAME, Long.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "lyricsURI", scope = ItemType.class)
    public JAXBElement<String> createItemTypeLyricsURI(String value) {
        return new JAXBElement<String>(_ContainerTypeLyricsURI_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", name = "desc", scope = ItemType.class)
    public JAXBElement<DescType> createItemTypeDesc(DescType value) {
        return new JAXBElement<DescType>(_ContainerTypeDesc_QNAME, DescType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "objectUpdateID", scope = ItemType.class)
    public JAXBElement<Long> createItemTypeObjectUpdateID(Long value) {
        return new JAXBElement<Long>(_ContainerTypeObjectUpdateID_QNAME, Long.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "radioCallSign", scope = ItemType.class)
    public JAXBElement<String> createItemTypeRadioCallSign(String value) {
        return new JAXBElement<String>(_ContainerTypeRadioCallSign_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProgramIDType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "programID", scope = ItemType.class)
    public JAXBElement<ProgramIDType> createItemTypeProgramID(ProgramIDType value) {
        return new JAXBElement<ProgramIDType>(_ContainerTypeProgramID_QNAME, ProgramIDType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifiedDateTime }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "lastPlaybackTime", scope = ItemType.class)
    public JAXBElement<QualifiedDateTime> createItemTypeLastPlaybackTime(QualifiedDateTime value) {
        return new JAXBElement<QualifiedDateTime>(_ContainerTypeLastPlaybackTime_QNAME, QualifiedDateTime.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "epgProviderName", scope = ItemType.class)
    public JAXBElement<String> createItemTypeEpgProviderName(String value) {
        return new JAXBElement<String>(_ContainerTypeEpgProviderName_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RatingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "rating", scope = ItemType.class)
    public JAXBElement<RatingType> createItemTypeRating(RatingType value) {
        return new JAXBElement<RatingType>(_ContainerTypeRating_QNAME, RatingType.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "storageMedium", scope = ItemType.class)
    public JAXBElement<String> createItemTypeStorageMedium(String value) {
        return new JAXBElement<String>(_ContainerTypeStorageMedium_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "producer", scope = ItemType.class)
    public JAXBElement<String> createItemTypeProducer(String value) {
        return new JAXBElement<String>(_ContainerTypeProducer_QNAME, String.class, ItemType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "fmProvider", scope = ForeignMetadataType.class)
    public JAXBElement<String> createForeignMetadataTypeFmProvider(String value) {
        return new JAXBElement<String>(_ForeignMetadataTypeFmProvider_QNAME, String.class, ForeignMetadataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "fmId", scope = ForeignMetadataType.class)
    public JAXBElement<String> createForeignMetadataTypeFmId(String value) {
        return new JAXBElement<String>(_ForeignMetadataTypeFmId_QNAME, String.class, ForeignMetadataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FmElementsBodyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "fmBody", scope = ForeignMetadataType.class)
    public JAXBElement<FmElementsBodyType> createForeignMetadataTypeFmBody(FmElementsBodyType value) {
        return new JAXBElement<FmElementsBodyType>(_ForeignMetadataTypeFmBody_QNAME, FmElementsBodyType.class, ForeignMetadataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", name = "fmClass", scope = ForeignMetadataType.class)
    public JAXBElement<String> createForeignMetadataTypeFmClass(String value) {
        return new JAXBElement<String>(_ForeignMetadataTypeFmClass_QNAME, String.class, ForeignMetadataType.class, value);
    }

}
