//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(
	namespace = "urn:schemas-upnp-org:metadata-1-0/upnp/", 
	xmlns = { 
		@javax.xml.bind.annotation.XmlNs( prefix = "dc",
			namespaceURI = "http://purl.org/dc/elements/1.1/" ),
		@javax.xml.bind.annotation.XmlNs( prefix = "upnp",
			namespaceURI = "urn:schemas-upnp-org:metadata-1-0/upnp/" ),
		@javax.xml.bind.annotation.XmlNs( prefix = "",
			namespaceURI = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" )
	},
	elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)

package org.medee.playground.upnp.didllite.jaxb;