//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//


package org.medee.playground.upnp.didllite.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for radioBand.wc.values.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="radioBand.wc.values">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="AM"/>
 *     &lt;enumeration value="FM"/>
 *     &lt;enumeration value="Shortwave"/>
 *     &lt;enumeration value="Internet"/>
 *     &lt;enumeration value="Satellite"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "radioBand.wc.values", namespace = "urn:schemas-upnp-org:av:av")
@XmlEnum
public enum RadioBandWcValues {

    AM("AM"),
    FM("FM"),
    @XmlEnumValue("Shortwave")
    SHORTWAVE("Shortwave"),
    @XmlEnumValue("Internet")
    INTERNET("Internet"),
    @XmlEnumValue("Satellite")
    SATELLITE("Satellite");
    private final String value;

    RadioBandWcValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RadioBandWcValues fromValue(String v) {
        for (RadioBandWcValues c: RadioBandWcValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
