//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//


package org.medee.playground.upnp.didllite.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rating.MPAA.ORG.values.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="rating.MPAA.ORG.values">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="G"/>
 *     &lt;enumeration value="PG"/>
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="PG-13"/>
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="NC-17"/>
 *     &lt;enumeration value="NR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "rating.MPAA.ORG.values", namespace = "urn:schemas-upnp-org:av:av")
@XmlEnum
public enum RatingMPAAORGValues {

    G("G"),
    PG("PG"),
    R("R"),
    @XmlEnumValue("PG-13")
    PG_13("PG-13"),
    @XmlEnumValue("NC-17")
    NC_17("NC-17"),
    NR("NR");
    private final String value;

    RatingMPAAORGValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RatingMPAAORGValues fromValue(String v) {
        for (RatingMPAAORGValues c: RatingMPAAORGValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
