//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//


package org.medee.playground.upnp.didllite.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rating.ESRB.ORG.values.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="rating.ESRB.ORG.values">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="EC"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="E10+"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="AO"/>
 *     &lt;enumeration value="RP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "rating.ESRB.ORG.values", namespace = "urn:schemas-upnp-org:av:av")
@XmlEnum
public enum RatingESRBORGValues {

    EC("EC"),
    E("E"),
    @XmlEnumValue("E10+")
    E_10("E10+"),
    T("T"),
    M("M"),
    AO("AO"),
    RP("RP");
    private final String value;

    RatingESRBORGValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RatingESRBORGValues fromValue(String v) {
        for (RatingESRBORGValues c: RatingESRBORGValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
