//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//


package org.medee.playground.upnp.didllite.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rating.TVGUIDELINES.ORG.values.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="rating.TVGUIDELINES.ORG.values">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="TV-Y"/>
 *     &lt;enumeration value="TV-Y7"/>
 *     &lt;enumeration value="TV-Y7FV"/>
 *     &lt;enumeration value="TV-G"/>
 *     &lt;enumeration value="TV-PG"/>
 *     &lt;enumeration value="TV-14"/>
 *     &lt;enumeration value="TV-MA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "rating.TVGUIDELINES.ORG.values", namespace = "urn:schemas-upnp-org:av:av")
@XmlEnum
public enum RatingTVGUIDELINESORGValues {

    @XmlEnumValue("TV-Y")
    TV_Y("TV-Y"),
    @XmlEnumValue("TV-Y7")
    TV_Y_7("TV-Y7"),
    @XmlEnumValue("TV-Y7FV")
    TV_Y_7_FV("TV-Y7FV"),
    @XmlEnumValue("TV-G")
    TV_G("TV-G"),
    @XmlEnumValue("TV-PG")
    TV_PG("TV-PG"),
    @XmlEnumValue("TV-14")
    TV_14("TV-14"),
    @XmlEnumValue("TV-MA")
    TV_MA("TV-MA");
    private final String value;

    RatingTVGUIDELINESORGValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RatingTVGUIDELINESORGValues fromValue(String v) {
        for (RatingTVGUIDELINESORGValues c: RatingTVGUIDELINESORGValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
