//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//


package org.medee.playground.upnp.didllite.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 * 				A 'res' element indentifies a resource.
 * 				A resource is typically some type of binary asset,
 * 				such as a photo, song, video, etc.
 * 				A 'res' element contains a URI that identifies the resource
 * 			
 * 
 * <p>Java class for res.type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="res.type">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>anyURI">
 *       &lt;attGroup ref="{urn:schemas-upnp-org:metadata-1-0/upnp/}dateTime.attr.group"/>
 *       &lt;attribute name="importUri" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="protocolInfo" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="size" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="duration" type="{urn:schemas-upnp-org:av:av}duration.cds1" />
 *       &lt;attribute name="bitrate" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="sampleFrequency" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="bitsPerSample" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="nrAudioChannels" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="resolution">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[0-9]+x[0-9]+"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="colorDepth" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="tspec" type="{urn:schemas-upnp-org:av:av}string.len.0_256" />
 *       &lt;attribute name="allowedUse" type="{urn:schemas-upnp-org:av:av}csv.1_.allowedUse" />
 *       &lt;attribute name="validityStart" type="{urn:schemas-upnp-org:av:av}dateTime" />
 *       &lt;attribute name="validityEnd" type="{urn:schemas-upnp-org:av:av}dateTime" />
 *       &lt;attribute name="remainingTime" type="{urn:schemas-upnp-org:av:av}unsignedDuration" />
 *       &lt;attribute name="usageInfo" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rightsInfoURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="contentInfoURI" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="recordQuality" type="{urn:schemas-upnp-org:av:av}csv.1_.colonDelimPairs" />
 *       &lt;attribute name="protection" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "res.type", namespace = "urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/", propOrder = {
    "value"
})
public class ResType {

    @XmlValue
    @XmlSchemaType(name = "anyURI")
    protected String value;
    @XmlAttribute(name = "importUri")
    @XmlSchemaType(name = "anyURI")
    protected String importUri;
    @XmlAttribute(name = "protocolInfo", required = true)
    protected String protocolInfo;
    @XmlAttribute(name = "size")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger size;
    @XmlAttribute(name = "duration")
    protected String duration;
    @XmlAttribute(name = "bitrate")
    @XmlSchemaType(name = "unsignedInt")
    protected Long bitrate;
    @XmlAttribute(name = "sampleFrequency")
    @XmlSchemaType(name = "unsignedInt")
    protected Long sampleFrequency;
    @XmlAttribute(name = "bitsPerSample")
    @XmlSchemaType(name = "unsignedInt")
    protected Long bitsPerSample;
    @XmlAttribute(name = "nrAudioChannels")
    @XmlSchemaType(name = "unsignedInt")
    protected Long nrAudioChannels;
    @XmlAttribute(name = "resolution")
    protected String resolution;
    @XmlAttribute(name = "colorDepth")
    @XmlSchemaType(name = "unsignedInt")
    protected Long colorDepth;
    @XmlAttribute(name = "tspec")
    protected String tspec;
    @XmlAttribute(name = "allowedUse")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String allowedUse;
    @XmlAttribute(name = "validityStart")
    protected XMLGregorianCalendar validityStart;
    @XmlAttribute(name = "validityEnd")
    protected XMLGregorianCalendar validityEnd;
    @XmlAttribute(name = "remainingTime")
    protected String remainingTime;
    @XmlAttribute(name = "usageInfo")
    protected String usageInfo;
    @XmlAttribute(name = "rightsInfoURI")
    @XmlSchemaType(name = "anyURI")
    protected String rightsInfoURI;
    @XmlAttribute(name = "contentInfoURI")
    @XmlSchemaType(name = "anyURI")
    protected String contentInfoURI;
    @XmlAttribute(name = "recordQuality")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String recordQuality;
    @XmlAttribute(name = "protection")
    protected String protection;
    @XmlAttribute(name = "daylightSaving", required = true)
    protected DaylightSavingType daylightSaving;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the importUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportUri() {
        return importUri;
    }

    /**
     * Sets the value of the importUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportUri(String value) {
        this.importUri = value;
    }

    /**
     * Gets the value of the protocolInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocolInfo() {
        return protocolInfo;
    }

    /**
     * Sets the value of the protocolInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocolInfo(String value) {
        this.protocolInfo = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSize(BigInteger value) {
        this.size = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuration(String value) {
        this.duration = value;
    }

    /**
     * Gets the value of the bitrate property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBitrate() {
        return bitrate;
    }

    /**
     * Sets the value of the bitrate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBitrate(Long value) {
        this.bitrate = value;
    }

    /**
     * Gets the value of the sampleFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSampleFrequency() {
        return sampleFrequency;
    }

    /**
     * Sets the value of the sampleFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSampleFrequency(Long value) {
        this.sampleFrequency = value;
    }

    /**
     * Gets the value of the bitsPerSample property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBitsPerSample() {
        return bitsPerSample;
    }

    /**
     * Sets the value of the bitsPerSample property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBitsPerSample(Long value) {
        this.bitsPerSample = value;
    }

    /**
     * Gets the value of the nrAudioChannels property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getNrAudioChannels() {
        return nrAudioChannels;
    }

    /**
     * Sets the value of the nrAudioChannels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setNrAudioChannels(Long value) {
        this.nrAudioChannels = value;
    }

    /**
     * Gets the value of the resolution property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * Sets the value of the resolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResolution(String value) {
        this.resolution = value;
    }

    /**
     * Gets the value of the colorDepth property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getColorDepth() {
        return colorDepth;
    }

    /**
     * Sets the value of the colorDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setColorDepth(Long value) {
        this.colorDepth = value;
    }

    /**
     * Gets the value of the tspec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTspec() {
        return tspec;
    }

    /**
     * Sets the value of the tspec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTspec(String value) {
        this.tspec = value;
    }

    /**
     * Gets the value of the allowedUse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowedUse() {
        return allowedUse;
    }

    /**
     * Sets the value of the allowedUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowedUse(String value) {
        this.allowedUse = value;
    }

    /**
     * Gets the value of the validityStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidityStart() {
        return validityStart;
    }

    /**
     * Sets the value of the validityStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidityStart(XMLGregorianCalendar value) {
        this.validityStart = value;
    }

    /**
     * Gets the value of the validityEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidityEnd() {
        return validityEnd;
    }

    /**
     * Sets the value of the validityEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidityEnd(XMLGregorianCalendar value) {
        this.validityEnd = value;
    }

    /**
     * Gets the value of the remainingTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemainingTime() {
        return remainingTime;
    }

    /**
     * Sets the value of the remainingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemainingTime(String value) {
        this.remainingTime = value;
    }

    /**
     * Gets the value of the usageInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsageInfo() {
        return usageInfo;
    }

    /**
     * Sets the value of the usageInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsageInfo(String value) {
        this.usageInfo = value;
    }

    /**
     * Gets the value of the rightsInfoURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRightsInfoURI() {
        return rightsInfoURI;
    }

    /**
     * Sets the value of the rightsInfoURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRightsInfoURI(String value) {
        this.rightsInfoURI = value;
    }

    /**
     * Gets the value of the contentInfoURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContentInfoURI() {
        return contentInfoURI;
    }

    /**
     * Sets the value of the contentInfoURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContentInfoURI(String value) {
        this.contentInfoURI = value;
    }

    /**
     * Gets the value of the recordQuality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordQuality() {
        return recordQuality;
    }

    /**
     * Sets the value of the recordQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordQuality(String value) {
        this.recordQuality = value;
    }

    /**
     * Gets the value of the protection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtection() {
        return protection;
    }

    /**
     * Sets the value of the protection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtection(String value) {
        this.protection = value;
    }

    /**
     * Gets the value of the daylightSaving property.
     * 
     * @return
     *     possible object is
     *     {@link DaylightSavingType }
     *     
     */
    public DaylightSavingType getDaylightSaving() {
        return daylightSaving;
    }

    /**
     * Sets the value of the daylightSaving property.
     * 
     * @param value
     *     allowed object is
     *     {@link DaylightSavingType }
     *     
     */
    public void setDaylightSaving(DaylightSavingType value) {
        this.daylightSaving = value;
    }

}
