//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//


package org.medee.playground.upnp.didllite.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for searchClass.type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="searchClass.type">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;urn:schemas-upnp-org:metadata-1-0/upnp/>class.type">
 *       &lt;attribute name="includeDerived" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "searchClass.type")
public class SearchClassType
    extends ClassType
{

    @XmlAttribute(name = "includeDerived", required = true)
    protected boolean includeDerived;

    /**
     * Gets the value of the includeDerived property.
     * 
     */
    public boolean isIncludeDerived() {
        return includeDerived;
    }

    /**
     * Sets the value of the includeDerived property.
     * 
     */
    public void setIncludeDerived(boolean value) {
        this.includeDerived = value;
    }

}
