//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.20 at 11:48:06 PM CEST 
//


package org.medee.playground.upnp.didllite.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for string.const.FIRST-RUN.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="string.const.FIRST-RUN">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FIRST-RUN"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "string.const.FIRST-RUN", namespace = "urn:schemas-upnp-org:av:av")
@XmlEnum
public enum StringConstFIRSTRUN {

    @XmlEnumValue("FIRST-RUN")
    FIRST_RUN("FIRST-RUN");
    private final String value;

    StringConstFIRSTRUN(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StringConstFIRSTRUN fromValue(String v) {
        for (StringConstFIRSTRUN c: StringConstFIRSTRUN.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
